/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 * 
 * @author rajabatu
 *
 */
public class Problem002_EvenFibonacciNumbers {

	public static void main(String[] args) {

		long pref;
		long curr = 2;
		long next = 8;
		
		long i = 1;
		long sum = 2;
		
		while (next < 4000000) 
		{
			System.out.println(i + " : " + next);
			
			sum += next;
			System.out.println("sum = " + sum);
			
			pref = curr;
			
			curr = next;
			
			next = (4 * curr) + pref;
			
			i++;
		}
		
		System.out.println("sum = " + sum);
	}

}
